<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="description" content="SPECTECHNOLOGY connects Irish home projects and architects with Polish manufacturers of bespoke timber-frame house kits.">
  <meta name="theme-color" content="#10241d">
  <title>SPECTECHNOLOGY — Designed in Ireland. Made in Poland.</title>
  <link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='14' fill='%2310241d'/%3E%3Cpath d='M12 35 32 17l20 18v14H39V35H25v14H12z' fill='%23c8f169'/%3E%3C/svg%3E">
  <link rel="stylesheet" href="assets/site.css">
  <script src="assets/site.js" defer></script>
</head>
<body>
  <header class="site-header">
    <a class="brand" href="#top"><img src="noBgColor.png" alt="SPECTECHNOLOGY S.A."></a>
    <nav><a href="#how" data-i18n="nav.how">How it works</a><a href="#network" data-i18n="nav.for">Who it is for</a><a href="#ireland">Ireland</a></nav>
    <div class="header-actions"><div class="language"><button data-lang="en" class="active">EN</button><button data-lang="pl">PL</button></div><button class="outline open-register" data-role="client" data-i18n="nav.join">Join the network</button></div>
  </header>
  <main id="top">
    <section class="hero">
      <img src="assets/images/hero-ireland.png" alt="Contemporary timber-frame home in Ireland">
      <div class="shade"></div>
      <div class="hero-copy"><p class="eyebrow" data-i18n="hero.eye">POLAND × IRELAND · TIMBER-FRAME HOMES</p><h1 data-i18n="hero.title">Designed in Ireland. Made in Poland.</h1><p data-i18n="hero.text">We connect Irish clients and architects with Polish manufacturers who engineer and produce bespoke timber-frame house kits for delivery and installation in Ireland.</p><div class="actions"><button class="primary open-register" data-role="client" data-i18n="hero.project">I have a project</button><button class="glass open-register" data-role="manufacturer" data-i18n="hero.maker">I manufacture in Poland</button></div></div>
      <div class="hero-note"><b>PL → IE</b><span data-i18n="hero.note">One route from architectural brief to installed structure.</span></div>
    </section>
    <section class="intro layout"><span class="index">01 — THE BRIDGE</span><div><h2 data-i18n="intro.title">Not a crew sent abroad. A home engineered before it travels.</h2><p data-i18n="intro.text">The concept starts in Ireland. A qualified Polish partner translates it into a compliant timber-frame package, manufactures it under controlled conditions and prepares it for transport and efficient on-site assembly.</p></div></section>
    <section id="how" class="split dark"><div class="photo"><img src="assets/images/factory-poland.png" alt="Timber-frame panel production in Poland"></div><div class="split-copy"><p class="eyebrow" data-i18n="process.eye">MADE TO THE IRISH BRIEF</p><h2 data-i18n="process.title">A controlled manufacturing process in Poland.</h2><ol><li><b>01</b><div><strong data-i18n="process.a">Qualify the project</strong><p data-i18n="process.at">Site, brief, programme and budget.</p></div></li><li><b>02</b><div><strong data-i18n="process.b">Align the design</strong><p data-i18n="process.bt">Architect, manufacturer and Irish requirements.</p></div></li><li><b>03</b><div><strong data-i18n="process.c">Manufacture the kit</strong><p data-i18n="process.ct">Bespoke frame and panels produced in Poland.</p></div></li><li><b>04</b><div><strong data-i18n="process.d">Deliver and install</strong><p data-i18n="process.dt">Planned transport and assembly in Ireland.</p></div></li></ol></div></section>
    <section id="network" class="network layout"><span class="index">02 — NETWORK</span><div><h2 data-i18n="network.title">One platform. Three ways in.</h2><div class="cards"><article><small>IRELAND</small><h3 data-i18n="network.client">Clients & developers</h3><p data-i18n="network.clientText">Bring a site, a need or a concept. We identify a suitable production route and Polish partners.</p><button class="link open-register" data-role="client" data-i18n="network.clientCta">Register a project →</button></article><article><small>IRELAND</small><h3 data-i18n="network.arch">Architects</h3><p data-i18n="network.archText">Include real Polish manufacturing capabilities, systems and logistics from the first concept.</p><button class="link open-register" data-role="architect" data-i18n="network.archCta">Join as an architect →</button></article><article><small>POLSKA</small><h3 data-i18n="network.maker">Manufacturers</h3><p data-i18n="network.makerText">Present your timber-frame capability, references and documentation to qualified Irish enquiries.</p><button class="link open-register" data-role="manufacturer" data-i18n="network.makerCta">Become a partner →</button></article></div></div></section>
    <section class="transport"><img src="assets/images/poland-ireland-logistics.png" alt="Modular home transported from Poland to Ireland"><div><p class="eyebrow">POLAND → IRELAND</p><h2 data-i18n="transport.title">The house travels. The process stays connected.</h2><p data-i18n="transport.text">SPECTECHNOLOGY coordinates the commercial and technical dialogue between the Irish brief and the Polish production team.</p></div></section>
    <section id="ireland" class="split garden"><div class="photo"><img src="assets/images/auxiliary-home-ireland.png" alt="Compact auxiliary home in an Irish garden"></div><div class="split-copy"><p class="eyebrow" data-i18n="garden.eye">AN EMERGING IRISH OPPORTUNITY</p><h2 data-i18n="garden.title">Compact auxiliary homes, ready for a smarter supply chain.</h2><p data-i18n="garden.text">Ireland is progressing planning exemptions for certain detached auxiliary homes. Government material published in April 2026 describes proposed units between 32 and 45 m², subject to conditions.</p><div class="policy"><b>32–45 m²</b><span data-i18n="garden.note">proposed range — eligibility and commencement must be checked for each site</span></div><a href="https://www.gov.ie/en/department-of-housing-local-government-and-heritage/press-releases/government-announces-changes-to-planning-exemptions-regulations/" target="_blank" rel="noopener" data-i18n="garden.source">Official government announcement ↗</a></div></section>
    <section class="platform layout"><span class="index">03 — PLATFORM</span><div><h2 data-i18n="platform.title">A bilingual marketplace, built to grow.</h2><p data-i18n="platform.text">Registered clients, architects and manufacturers form the foundation of a moderated catalogue and project-matching workflow available in English and Polish.</p><div class="facts"><div><b>EN / PL</b><span data-i18n="platform.one">Both markets, both languages</span></div><div><b>3</b><span data-i18n="platform.two">User profiles</span></div><div><b>1</b><span data-i18n="platform.three">Coordinated route to delivery</span></div></div></div></section>
    <section class="closing"><p class="eyebrow" data-i18n="closing.eye">START THE CONVERSATION</p><h2 data-i18n="closing.title">What are you looking to build — or bring to Ireland?</h2><button class="primary open-register" data-role="client" data-i18n="closing.cta">Join the SPECTECHNOLOGY network</button></section>
  </main>
  <footer><div><img src="noBgColor.png" alt="SPECTECHNOLOGY"><p>SPECTECHNOLOGY SPÓŁKA AKCYJNA<br>ul. Fort Wola 22, 01-258 Warszawa, Polska</p></div><div><p>KRS 0001207307 · NIP 5273193733<br>REGON 543323910</p><a href="mailto:office@spectechnology.pl">office@spectechnology.pl</a></div></footer>
  <dialog id="registerDialog"><button class="close" aria-label="Close">×</button><p class="eyebrow" data-i18n="form.eye">JOIN THE NETWORK</p><h2 data-i18n="form.title">Tell us where you fit.</h2><form id="registerForm"><label><span data-i18n="form.role">I am registering as</span><select name="role" required><option value="client" data-i18n="form.client">Irish client / developer</option><option value="architect" data-i18n="form.arch">Architect in Ireland</option><option value="manufacturer" data-i18n="form.maker">Polish manufacturer</option></select></label><div class="form-row"><label><span data-i18n="form.name">Name</span><input name="name" required></label><label><span data-i18n="form.company">Company</span><input name="company"></label></div><label><span>Email</span><input type="email" name="email" required></label><label><span data-i18n="form.details">Project or capability summary</span><textarea name="details" required></textarea></label><label class="check"><input type="checkbox" name="consent" value="1" required><span data-i18n="form.consent">I agree that SPECTECHNOLOGY may contact me about this enquiry.</span></label><input type="hidden" name="language" value="en"><button class="primary submit" type="submit" data-i18n="form.submit">Create my profile</button><p id="formStatus" aria-live="polite"></p></form></dialog>
</body>
</html>
